FROM tomcat:9.0.0.M21-jre8-alpine

MAINTAINER Nicolas Peruch <nicolas.peruch@ilegra.com>

COPY /build/libs/jt.calculator-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/jt.calculator-1.0-SNAPSHOT.war

CMD ["catalina.sh","run"]



